### ISSUE TITLE
LessonText TODO list

### ISSUE THREAD

**Issue by sgoshorn** [CCALI/CALI-Author-Viewer-5#44]
List of issues from Deb Cohen about LessonText for authors which includes aggregate score data. Made a GIT issue so it's not lost. 

- [ ] is the bar % right/wrong? should be defined
- [ ] some questions are designed to be wrong - ‘a common trap’. Any way to flag these for future reference?
- [ ] Common Trap identifier would be helpful in LessonLive to know WHY students got a q wrong. Allow teacher to focus on unexpected wrong questions instead of expected wrong questions
- [ ] Exclude all faculty score saves - requires filtering for students (exclude techs, librarians too)
- [x] all summary data at top of LessonText before body of questions
- [ ] as author, is it useful for essays to be included in lesson? Maybe a word count in summary report, Maybe use a histogram on number of words typed?
- [ ] Only teacher assigning lessons would find actual essays useful so include in their reports
- [ ] Include sort by times to see if a page is generally useful or not. e.g., a branch that is rarely taken may need to be redesigned. 
- [ ] wants to compare class to country to show students they are not unique when they get the same material wrong in the same way
